# -*- coding: utf-8 -*-
"""Hand translations for remaining gaps: ntgl, moonlight, create, modernfix,
farmersdelight, supplementaries. Run on homelab via gap-fill.py."""

NTGL = {
    "block.ntgl.workbench": "组装工作台",
    "button.categories.ntgl": "NTGL 武器",
    "button.controls.ntgl": "NTGL 武器",
    "container.ntgl.attachments": "改装配件",
    "container.ntgl.attachments.window_help": "点击移动和旋转",
    "container.ntgl.workbench": "组装工作台",
    "death.attack.bullet": "%1$s被射杀了",
    "death.attack.bullet.item": "%1$s被%2$s用%3$s射杀了",
    "death.attack.bullet.player": "%1$s被%2$s射杀了",
    "death.attack.energy": "%1$s被蒸发了",
    "death.attack.energy.item": "%1$s被%2$s用%3$s蒸发了",
    "death.attack.energy.player": "%1$s被%2$s蒸发了",
    "death.attack.explosive": "%1$s爆炸了",
    "death.attack.explosive.player": "%1$s被%2$s炸死了",
    "death.attack.explosive.player.item": "%1$s被%2$s用%3$s炸死了",
    "death.attack.fire": "%1$s被烧成了灰",
    "death.attack.fire.player": "%1$s被%2$s烧成了灰",
    "death.attack.fire.player.item": "%1$s被%2$s用%3$s烧成了灰",
    "effect.ntgl.blinded": "致盲",
    "effect.ntgl.deafened": "致聋",
    "enchantment.ntgl.accelerator": "加速器",
    "enchantment.ntgl.accelerator.desc": "提高发射物的飞行速度，使其造成更高伤害",
    "enchantment.ntgl.collateral": "贯穿",
    "enchantment.ntgl.collateral.desc": "使发射的子弹可以穿透多个实体",
    "enchantment.ntgl.fire_starter": "纵火者",
    "enchantment.ntgl.fire_starter.desc": "发射的子弹命中时会点燃方块和实体",
    "enchantment.ntgl.lightweight": "轻量化",
    "enchantment.ntgl.lightweight.desc": "降低武器重量，提高开镜速度",
    "enchantment.ntgl.over_capacity": "超载弹容",
    "enchantment.ntgl.over_capacity.desc": "提高武器的弹药容量",
    "enchantment.ntgl.puncturing": "穿甲",
    "enchantment.ntgl.puncturing.desc": "使子弹有几率造成暴击伤害",
    "enchantment.ntgl.quick_hands": "快手",
    "enchantment.ntgl.quick_hands.desc": "提高武器的换弹速度",
    "enchantment.ntgl.reclaimed": "回收",
    "enchantment.ntgl.reclaimed.desc": "开火时有几率不消耗子弹",
    "enchantment.ntgl.trigger_finger": "扣指如飞",
    "enchantment.ntgl.trigger_finger.desc": "提高武器的射击速度",
    "entity.ntgl.flame_projectile": "火焰",
    "entity.ntgl.grenade": "手雷",
    "entity.ntgl.projectile": "投射物",
    "entity.ntgl.spear": "长矛",
    "entity.ntgl.throwable_grenade": "手雷",
    "entity.ntgl.throwable_stun_grenade": "闪光弹",
    "fire_mode.ntgl.auto": "全自动",
    "fire_mode.ntgl.burst": "点射",
    "fire_mode.ntgl.multi": "多发齐射",
    "fire_mode.ntgl.semi": "半自动",
    "gui.ntgl.assemble": "组装",
    "gui.ntgl.show_remaining": "显示剩余",
    "gui.ntgl.workbench.assemble": "组装",
    "gui.ntgl.workbench.show_remaining": "显示剩余",
    "gui.ntgl.workbench.tab.ammo": "弹药",
    "gui.ntgl.workbench.tab.attachments": "配件",
    "gui.ntgl.workbench.tab.heavy": "重型",
    "gui.ntgl.workbench.tab.melee": "近战武器",
    "gui.ntgl.workbench.tab.misc": "杂项",
    "gui.ntgl.workbench.tab.pistol": "手枪",
    "gui.ntgl.workbench.tab.rifle": "步枪",
    "gui.ntgl.workbench.tab.shotgun": "霰弹枪",
    "gui.ntgl.workbench.tab.weapons": "武器",
    "info.ntgl.additional": "附加",
    "info.ntgl.alternative": "替代",
    "info.ntgl.ammo": "弹药：%s",
    "info.ntgl.ammo_type": "弹药类型：%s",
    "info.ntgl.attachment_help": "在游戏中按 %s 改装配件",
    "info.ntgl.burnable": "燃料",
    "info.ntgl.causes_fire": "造成点燃",
    "info.ntgl.custom": "自定义",
    "info.ntgl.damage": "伤害：%s",
    "info.ntgl.destroys_blocks": "可破坏方块",
    "info.ntgl.explodes_on_contact": "接触即爆",
    "info.ntgl.explosionDamage": "爆炸伤害：%s",
    "info.ntgl.explosionRadius": "爆炸半径：%s",
    "info.ntgl.fire_mode": "射击模式：%s",
    "info.ntgl.fuse_time": "引信时间：%s秒",
    "info.ntgl.header.attachments": "[ 配件 ]",
    "info.ntgl.header.bash": "[ 近战突刺 ]",
    "info.ntgl.header.handling": "[ 操控 ]",
    "info.ntgl.hold_shift": "按住 [SHIFT] 查看详情",
    "info.ntgl.ignore_ammo": "无限弹药",
    "info.ntgl.knockback": "击退：%s",
    "info.ntgl.max_ammo": "最大弹药：%s",
    "info.ntgl.melee": "近战",
    "info.ntgl.melee_damage": "近战伤害：%s",
    "info.ntgl.none": "无",
    "info.ntgl.primary": "主属性",
    "info.ntgl.rate": "每秒射速：%s",
    "info.ntgl.reload_time": "换弹时间：%s秒",
    "info.ntgl.scope": "瞄具",
    "info.ntgl.secondary": "副属性",
    "info.ntgl.shot": "射击",
    "info.ntgl.spread": "散布：%s",
    "info.ntgl.throw": "投掷",
    "info.ntgl.water": "水下",
    "item.minecraft.lingering_potion.effect.blinding": "滞留型致盲药水",
    "item.minecraft.lingering_potion.effect.deafening": "滞留型致聋药水",
    "item.minecraft.potion.effect.blinding": "致盲药水",
    "item.minecraft.potion.effect.deafening": "致聋药水",
    "item.ntgl.grenade": "手雷",
    "item.ntgl.light_grip": "轻型握把",
    "item.ntgl.light_stock": "轻型枪托",
    "item.ntgl.long_scope": "长程瞄具",
    "item.ntgl.medium_scope": "中程瞄具",
    "item.ntgl.powdergun": "黑火药步枪",
    "item.ntgl.round10mm": "10mm 弹",
    "item.ntgl.round38": ".38 弹",
    "item.ntgl.round380": ".380 弹",
    "item.ntgl.round44": ".44 弹",
    "item.ntgl.round45": ".45 弹",
    "item.ntgl.round50": ".50 弹",
    "item.ntgl.round556": "5.56 弹",
    "item.ntgl.round5mm": "5mm 弹",
    "item.ntgl.shell": "霰弹",
    "item.ntgl.short_scope": "短程瞄具",
    "item.ntgl.silencer": "消音器",
    "item.ntgl.specialised_grip": "专用握把",
    "item.ntgl.steel_ball": ".50 钢珠",
    "item.ntgl.stun_grenade": "闪光弹",
    "item.ntgl.tactical_stock": "战术枪托",
    "item.ntgl.weighted_stock": "配重枪托",
    "itemGroup.ntgl": "NTGL 枪械",
    "itemGroup.ntgl.blocks": "NTGL 方块",
    "itemGroup.ntgl.example": "NTGL 示例",
    "itemGroup.weapons": "NTGL",
    "key.categories.debug": "NTGL 调试",
    "key.categories.ntgl": "NTGL 武器",
    "key.categories.ntgl.armor": "NTGL 护甲",
    "key.ntgl.alt": "替代攻击",
    "key.ntgl.ammo_select": "选择弹药",
    "key.ntgl.attachments": "改装配件",
    "key.ntgl.debug_rx_add": "X 轴旋转 +",
    "key.ntgl.debug_rx_sub": "X 轴旋转 -",
    "key.ntgl.debug_ry_add": "Y 轴旋转 +",
    "key.ntgl.debug_ry_sub": "Y 轴旋转 -",
    "key.ntgl.debug_rz_add": "Z 轴旋转 +",
    "key.ntgl.debug_rz_sub": "Z 轴旋转 -",
    "key.ntgl.debug_x_add": "X 位置 +",
    "key.ntgl.debug_x_sub": "Z 位置 -",
    "key.ntgl.debug_y_add": "Y 位置 +",
    "key.ntgl.debug_y_sub": "X 位置 -",
    "key.ntgl.debug_z_add": "Z 位置 +",
    "key.ntgl.debug_z_sub": "Y 位置 -",
    "key.ntgl.fire_select": "切换射击模式",
    "key.ntgl.inspect": "检视武器",
    "key.ntgl.key_tips": "显示按键提示",
    "key.ntgl.leave": "退出护甲",
    "key.ntgl.melee": "近战攻击",
    "key.ntgl.reload": "换弹",
    "key.ntgl.unload": "退弹",
    "minecraft.crosshair.default": "默认",
    "ntgl.action.aim": "开镜",
    "ntgl.action.reload": "换弹",
    "ntgl.action.shoot": "射击",
    "ntgl.action.steady_aim": "稳息瞄准",
    "ntgl.button.aim": "机瞄开镜",
    "ntgl.button.ammo_select": "选择弹药类型",
    "ntgl.button.attachments": "改装配件",
    "ntgl.button.config.tooltip": "配置选项",
    "ntgl.button.fire_select": "选择射击模式",
    "ntgl.button.inspect": "检视武器",
    "ntgl.button.reload": "换弹 / 退弹",
    "ntgl.button.shoot": "射击武器",
    "ntgl.button.steadyAim": "稳息瞄准",
    "ntgl.category.workbench.materials": "材料",
    "ntgl.category.workbench.title": "组装中",
    "ntgl.chat.install_configured": "安装 %s 以访问配置选项",
    "ntgl.chat.open_curseforge_page": "打开 CurseForge 页面",
    "ntgl.crosshair.arrow": "箭头",
    "ntgl.crosshair.better_default": "增强默认",
    "ntgl.crosshair.box": "方框",
    "ntgl.crosshair.circle": "圆环",
    "ntgl.crosshair.dot": "圆点",
    "ntgl.crosshair.filled_circle": "实心圆",
    "ntgl.crosshair.hit_marker": "命中标记",
    "ntgl.crosshair.line": "十字线",
    "ntgl.crosshair.round": "圆形",
    "ntgl.crosshair.smiley": "笑脸",
    "ntgl.crosshair.square": "方形",
    "ntgl.crosshair.t": "T 形",
    "ntgl.crosshair.tech": "科技",
    "ntgl.option_list.no_items": "没有物品",
    "ntgl.options.adsSensitivity": "开镜灵敏度",
    "ntgl.options.adsSensitivity.format": "开镜灵敏度：%s",
    "ntgl.options.crosshair": "准星",
    "ntgl.options.gun_volume": "枪械",
    "ntgl.options.gun_volume_button": "枪声音量",
    "perk.ntgl.ads_speed": "开镜速度：%s",
    "perk.ntgl.entry.negative": "- %s",
    "perk.ntgl.entry.positive": "+ %s",
    "perk.ntgl.fire_modes": "射击模式：",
    "perk.ntgl.fire_volume": "枪声音量",
    "perk.ntgl.max_ammo": "最大弹药：%s",
    "perk.ntgl.melee_damage": "近战伤害：%s",
    "perk.ntgl.melee_distance": "近战距离：%s",
    "perk.ntgl.modified_damage": "武器伤害：%s",
    "perk.ntgl.projectile_amount": "每次射出弹丸数：%s",
    "perk.ntgl.projectile_life": "伤害距离：%s",
    "perk.ntgl.projectile_speed": "弹丸速度：%s",
    "perk.ntgl.projectile_spread": "弹丸散布：%s",
    "perk.ntgl.rate": "射速：%s",
    "perk.ntgl.recoil": "后坐力：%s",
    "perk.ntgl.silenced": "已消音",
    "perk.ntgl.sound_radius": "枪声传播半径",
    "perk.ntgl.title": "特性：",
    "slot.ntgl.attachment.barrel": "枪管",
    "slot.ntgl.attachment.grip": "握把",
    "slot.ntgl.attachment.incompatible": "这似乎装不上去……",
    "slot.ntgl.attachment.magazine": "弹匣",
    "slot.ntgl.attachment.melee": "近战",
    "slot.ntgl.attachment.muzzle": "枪口",
    "slot.ntgl.attachment.not_applicable": "§c不适用",
    "slot.ntgl.attachment.scope": "瞄具",
    "slot.ntgl.attachment.stock": "枪托",
    "slot.ntgl.attachment.under_barrel": "下挂",
    "subtitle.ntgl.attach": "安装配件",
    "subtitle.ntgl.cock": "武器上膛",
    "subtitle.ntgl.fire": "枪声",
    "subtitle.ntgl.fire.enchanted": "附魔枪声",
    "subtitle.ntgl.fire.silenced": "消音枪声",
    "subtitle.ntgl.grenade.pin": "拔掉手雷保险",
    "subtitle.ntgl.reload": "换弹中",
    "subtitle.ntgl.stun.explosion": "闪光弹爆炸",
    "subtitle.ntgl.stun.ring": "耳鸣",
    "title.ntgl.ammo_type": "弹药类型",
    "title.ntgl.default": "主武器",
    "title.ntgl.under_barrel": "下挂武器",
}

MOONLIGHT = {
    "block.moonlight.spawn_box": "刷怪箱方块",
    "commands.moonlight.added_map_marker": "已将地图装饰 %s 添加到当前物品",
    "commands.moonlight.back.empty": " 没有记录先前的位置",
    "commands.moonlight.back.invalid_dimension": "先前的位置所在的维度已卸载",
    "commands.moonlight.back.only_players": "只有玩家能使用 back 命令",
    "commands.moonlight.blockstate_stats": "总方块数：%1$s，总方块状态数：%2$s。附加信息已保存至 %3$s",
    "commands.moonlight.breeze.off": "旋风人调试渲染器已关闭",
    "commands.moonlight.breeze.on": "旋风人调试渲染器已开启",
    "commands.moonlight.collision.off": "碰撞渲染器已关闭",
    "commands.moonlight.collision.on": "碰撞渲染器已开启",
    "commands.moonlight.config.no_config": "模组 %s 没有配置界面",
    "commands.moonlight.dice": "掷出 D%1$d：%2$d",
    "commands.moonlight.frustum.captured": "已捕获视锥",
    "commands.moonlight.frustum.killed": "已清除视锥",
    "commands.moonlight.game_events.off": "游戏事件渲染器已关闭",
    "commands.moonlight.game_events.on": "游戏事件渲染器已开启",
    "commands.moonlight.goal_selector.add": "已为 %s 启用目标选择器调试渲染器",
    "commands.moonlight.goal_selector.off": "已禁用目标选择器调试渲染器",
    "commands.moonlight.goal_selector.on": "已启用目标选择器调试渲染器",
    "commands.moonlight.goal_selector.remove": "已为 %s 禁用目标选择器调试渲染器",
    "commands.moonlight.heightmap.off": "高度图渲染器已关闭",
    "commands.moonlight.heightmap.on": "高度图渲染器已开启",
    "commands.moonlight.light.off": "光照调试渲染器已关闭",
    "commands.moonlight.light.on": "光照调试渲染器已开启",
    "commands.moonlight.navigation.add": "已为 %s 启用寻路调试渲染器",
    "commands.moonlight.navigation.off": "已禁用寻路调试渲染器",
    "commands.moonlight.navigation.on": "已启用寻路调试渲染器",
    "commands.moonlight.navigation.remove": "已为 %s 禁用寻路调试渲染器",
    "commands.moonlight.neighbor_updates.off": "邻块更新渲染器已关闭",
    "commands.moonlight.neighbor_updates.on": "邻块更新渲染器已开启",
    "commands.moonlight.registry.copy_elements_names": "点击复制全部条目名称到剪贴板",
    "commands.moonlight.registry.dump.success": "已将注册表内容转储至 %s",
    "commands.moonlight.registry.element": "%s : %s",
    "commands.moonlight.registry.elements_count": "条目数：%s",
    "commands.moonlight.registry.error.unknown_registry": "未知注册表 %s",
    "commands.moonlight.registry.page_info": "%s <第 %s / %s 页>",
    "commands.moonlight.registry.registry_key": "%s",
    "commands.moonlight.section_path.off": "区块路径已隐藏",
    "commands.moonlight.section_path.on": "区块路径已显示",
    "commands.moonlight.section_visibility.off": "区块可见性已禁用",
    "commands.moonlight.section_visibility.on": "区块可见性已启用",
    "commands.moonlight.sky_light_sections.off": "天空光区块渲染器已关闭",
    "commands.moonlight.sky_light_sections.on": "天空光区块渲染器已开启",
    "commands.moonlight.smart_cull.off": "智能剔除已禁用",
    "commands.moonlight.smart_cull.on": "智能剔除已启用",
    "commands.moonlight.solid_faces.off": "固体面渲染器已关闭",
    "commands.moonlight.solid_faces.on": "固体面渲染器已开启",
    "commands.moonlight.structures.add": "已为 %s 启用结构边界调试渲染器",
    "commands.moonlight.structures.off": "已禁用结构边界调试渲染器",
    "commands.moonlight.structures.on": "已启用结构边界调试渲染器",
    "commands.moonlight.structures.remove": "已为 %s 禁用结构边界调试渲染器",
    "commands.moonlight.support.off": "支撑形状渲染器已关闭",
    "commands.moonlight.support.on": "支撑形状渲染器已开启",
    "commands.moonlight.water.off": "水体调试渲染器已关闭",
    "commands.moonlight.water.on": "水体调试渲染器已开启",
    "commands.moonlight.wireframe.off": "线框已禁用",
    "commands.moonlight.wireframe.on": "线框已启用",
    "commands.moonlight.world_gen_attempts.off": "世界生成尝试渲染器已关闭",
    "commands.moonlight.world_gen_attempts.on": "世界生成尝试渲染器已开启",
    "gui.moonlight.config.authors": "作者",
    "gui.moonlight.config.color_pick": "选取",
    "gui.moonlight.config.color_picker": "颜色选择器",
    "gui.moonlight.config.disabled_by": "被 %s 禁用",
    "gui.moonlight.config.discard.confirm": "放弃",
    "gui.moonlight.config.discard.message": "你有 %s 个未保存的更改。不保存直接离开？",
    "gui.moonlight.config.discard.title": "放弃更改？",
    "gui.moonlight.config.discover_by": "%s 的模组",
    "gui.moonlight.config.discover_loading": "正在获取模组列表",
    "gui.moonlight.config.discover_mods": "发现模组",
    "gui.moonlight.config.discover_no_results": "没有符合搜索的模组",
    "gui.moonlight.config.discover_offline": "无法连接模组列表。请检查网络连接。",
    "gui.moonlight.config.discover_title": "发现模组",
    "gui.moonlight.config.discover_title_by": "%s 的更多模组",
    "gui.moonlight.config.edit": "编辑",
    "gui.moonlight.config.edit_manually": "编辑文件",
    "gui.moonlight.config.favourite": "收藏",
    "gui.moonlight.config.json_hint": "输入 JSON…",
    "gui.moonlight.config.json_invalid": "无效的 JSON",
    "gui.moonlight.config.list_add": "添加条目",
    "gui.moonlight.config.list_entries": "编辑（%s）",
    "gui.moonlight.config.list_entry": "条目 %s",
    "gui.moonlight.config.list_remove": "移除条目",
    "gui.moonlight.config.map_duplicate_key": "存在重复键，仅保留最后一个",
    "gui.moonlight.config.mods_button": "模组",
    "gui.moonlight.config.mods_title": "可配置模组",
    "gui.moonlight.config.no_matches": "无匹配项",
    "gui.moonlight.config.open_folder": "打开配置文件夹",
    "gui.moonlight.config.reload.game": "需要重启游戏",
    "gui.moonlight.config.reload.world": "需要重载世界",
    "gui.moonlight.config.reload_needed.game": "部分更改需要重启游戏才能生效。",
    "gui.moonlight.config.reload_needed.title": "配置已保存",
    "gui.moonlight.config.reload_needed.world": "部分更改需要重载世界才能生效。",
    "gui.moonlight.config.reset": "重置为默认",
    "gui.moonlight.config.reset_all": "全部重置",
    "gui.moonlight.config.reset_all.message": "这会将此配置中的所有选项重置为默认值并立即保存。此操作无法撤销。",
    "gui.moonlight.config.reset_all.title": "重置所有选项？",
    "gui.moonlight.config.save": "保存",
    "gui.moonlight.config.save_count": "保存 %s",
    "gui.moonlight.config.schema_invalid": "无效值：%s",
    "gui.moonlight.config.schema_type": "类型",
    "gui.moonlight.config.search": "搜索…",
    "gui.moonlight.config.sort_ascending": "按 A-Z 排序",
    "gui.moonlight.config.sort_descending": "按 Z-A 排序",
    "gui.moonlight.config.unavailable.not_in_world": "此配置属于某个世界。请先加载世界再编辑。",
    "gui.moonlight.config.unavailable.server_controlled": "此配置由你连接的服务器设定。",
    "gui.moonlight.config.unfavourite": "取消收藏",
    "leaves_type.ulterlands.souldrained": "石化",
    "message.moonlight.cached": "缓存资源",
    "message.moonlight.cached_zipped": "压缩的缓存资源",
    "message.moonlight.merged_pack.description": "包含 %s 个模组的资源",
    "message.moonlight.merged_pack.title": "Moonlight 动态资源",
    "message.moonlight.runtime": "运行时资源",
    "message.moonlight.spawn_box_block.size": "刷怪箱尺寸",
    "moonlight.config.common.enabled": "启用",
    "moonlight.config.common.max": "最大",
    "moonlight.config.common.min": "最小",
    "moonlight.config.common.x": "X",
    "moonlight.config.common.y": "Y",
    "moonlight.config.common.z": "Z",
    "moonlight.configuration.config_screen": "配置界面",
    "moonlight.configuration.config_screen.config_item_carousel": "配置物品轮播",
    "moonlight.configuration.config_screen.config_item_carousel.description": "在模组的配置界面上显示一条缓慢滚动的模组物品条",
    "moonlight.configuration.config_screen.convert_foreign_configs": "转换外部配置",
    "moonlight.configuration.config_screen.convert_foreign_configs.description": "在 Moonlight 的界面内绘制其他模组的配置，而非它们自己的界面（仅 NeoForge）。GENERIC_ONLY 仅涵盖从未编写过自己界面的模组，ALWAYS 涵盖所有模组。按世界保存的服务端配置仅在世界打开时显示。尽力而为：无法显示的选项保持原样",
    "moonlight.configuration.config_screen.custom_config_screen": "自定义配置界面",
    "moonlight.configuration.config_screen.custom_config_screen.description": "使用 Moonlight 的配置界面。关闭时，配置将打开加载器自带的界面：NeoForge 自带的（或 Configured）、Cloth Config 或 Fabric 上的 YACL",
    "moonlight.configuration.config_screen.favourite_mods": "收藏模组",
    "moonlight.configuration.config_screen.favourite_mods.description": "置顶显示在模组界面的模组。点击模组卡片上的星标即可添加或移除",
    "moonlight.configuration.config_screen.mod_list_descending": "模组列表倒序",
    "moonlight.configuration.config_screen.mod_list_descending.description": "在模组界面按 Z 到 A 排序",
    "moonlight.configuration.config_screen.show_all_mod_configs": "显示所有模组配置",
    "moonlight.configuration.config_screen.show_all_mod_configs.description": "为每个带配置界面的已安装模组提供一张卡片，而不仅是使用 Moonlight 的模组。点击时打开它们自己的界面",
    "moonlight.configuration.general.consistent_entity_renderer_shading": "实体渲染器阴影一致性",
    "moonlight.configuration.general.consistent_entity_renderer_shading.description": "将 Minecraft 实体阴影修正为与方块完全一致（顶 1、北 0.8、西 0.6、下 0.5）。这样用方块渲染器或实体渲染的模型会与烘焙模型完全一致。不渲染 GUI 可避免其改变 GUI 中渲染的物品外观。注意与 Figura 模组存在已知兼容问题，装了 Figura 请保持默认",
    "moonlight.configuration.general.debug_renderers": "调试渲染器",
    "moonlight.configuration.general.debug_renderers.description": "启用一些调试渲染器。需要使用 /supp debug 命令才会发送对应数据",
    "moonlight.configuration.general.extra_children_debug": "额外子项调试",
    "moonlight.configuration.general.extra_children_debug.description": "启用后将列出每种方块类型的子项。子项列表也会通过 EXTRA_DEBUG 写入同一文件。注意：启用此项还需要同时启用 EXTRA_DEBUG",
    "moonlight.configuration.general.extra_debug": "额外调试",
    "moonlight.configuration.general.extra_debug.description": "仅用于调试目的。开启更多日志或 blocktypes_debug.txt 等调试功能，文件位于 ~/.minecraft/debug/dynamic_registry_dump…",
    "moonlight.configuration.general.faster_cache_search": "更快的缓存搜索",
    "moonlight.configuration.general.faster_cache_search.description": "让动态资源缓存使用树形结构索引，大幅加快查询速度，但可能占用一些内存。",
    "moonlight.configuration.general.global_datapacks_folder": "全局数据包文件夹",
    "moonlight.configuration.general.global_datapacks_folder.description": "全局数据包文件夹。存放其中数据包会自动加载到你的所有世界。留空字符串则禁用",
    "moonlight.configuration.general.lazy_map_upload": "地图纹理懒上传",
    "moonlight.configuration.general.lazy_map_upload.description": "仅地图标记变化时不上传地图纹理到 GPU。可能提升性能",
    "moonlight.configuration.general.maps_mipmap": "地图 Mipmap",
    "moonlight.configuration.general.maps_mipmap.description": "使用 mipmap 渲染地图纹理。远观效果大幅提升，在地图图集内同样有效。设为 0 则与原版一致不使用 mipmap",
    "moonlight.configuration.general.merge_dynamic_resource_packs": "合并动态资源包",
    "moonlight.configuration.general.merge_dynamic_resource_packs.description": "将所有使用此库的模组的动态资源包合并为单个资源包",
    "moonlight.configuration.general.multi_threaded_generation": "多线程生成",
    "moonlight.configuration.general.multi_threaded_generation.description": "为动态资源启用多线程生成（若支持）。在核心较多的系统上可提升性能。",
    "moonlight.configuration.general.tags_tooltips": "标签提示",
    "moonlight.configuration.general.tags_tooltips.description": "在物品提示中显示物品和方块标签",
    "moonlight.configuration.nested": "嵌套",
    "moonlight.configuration.nested.nested_float": "嵌套浮点",
    "moonlight.configuration.nested.nested_float.description": "位于嵌套子分类中的浮点值",
    "moonlight.configuration.test_bean": "测试 Bean",
    "moonlight.configuration.test_bean.count": "数量",
    "moonlight.configuration.test_bean.flag": "开关",
    "moonlight.configuration.test_bean.name": "名称",
    "moonlight.configuration.test_category": "测试分类",
    "moonlight.configuration.test_category.test_after_comment": "注释后声明测试",
    "moonlight.configuration.test_category.test_after_comment.description": "此注释声明于其自身 define 调用之后",
    "moonlight.configuration.test_category.test_block": "测试方块",
    "moonlight.configuration.test_category.test_block.description": "从注册表选取的方块，带图标",
    "moonlight.configuration.test_category.test_bool": "测试布尔",
    "moonlight.configuration.test_category.test_bool.description": "布尔特性，绘制为对/叉开关，符号旁带图标",
    "moonlight.configuration.test_category.test_color": "测试颜色",
    "moonlight.configuration.test_category.test_color.description": "ARGB 颜色，以十六进制字段编辑",
    "moonlight.configuration.test_category.test_color_no_alpha": "测试颜色（无透明度）",
    "moonlight.configuration.test_category.test_color_no_alpha.description": "不带 Alpha 通道的 RGB 颜色",
    "moonlight.configuration.test_category.test_date": "测试日期",
    "moonlight.configuration.test_category.test_double": "测试双精度",
    "moonlight.configuration.test_category.test_double.description": "双精度数，以文本字段编辑",
    "moonlight.configuration.test_category.test_double_slider": "测试双精度滑块",
    "moonlight.configuration.test_category.test_double_slider.description": "双精度数，以滑块编辑",
    "moonlight.configuration.test_category.test_dropdown": "测试下拉框",
    "moonlight.configuration.test_category.test_dropdown.description": "从下拉列表中选取的值",
    "moonlight.configuration.test_category.test_dropdown_list": "测试下拉列表",
    "moonlight.configuration.test_category.test_dropdown_list.description": "字符串列表，每个条目都从下拉框中选取",
    "moonlight.configuration.test_category.test_enum": "测试枚举",
    "moonlight.configuration.test_category.test_enum.description": "枚举，以循环按钮编辑",
    "moonlight.configuration.test_category.test_game_restart": "测试（需重启游戏）",
    "moonlight.configuration.test_category.test_game_restart.description": "需要重启游戏才能生效的值（显示电源图标）",
    "moonlight.configuration.test_category.test_int": "测试整数",
    "moonlight.configuration.test_category.test_int.description": "整数，以文本字段编辑",
    "moonlight.configuration.test_category.test_int_slider": "测试整数滑块",
    "moonlight.configuration.test_category.test_int_slider.description": "整数，以滑块编辑",
    "moonlight.configuration.test_category.test_item": "测试物品",
    "moonlight.configuration.test_category.test_item.description": "从注册表选取的物品，带图标",
    "moonlight.configuration.test_category.test_item_list": "测试物品列表",
    "moonlight.configuration.test_category.test_item_list.description": "物品列表，每个条目从带图标的物品下拉框中选取",
    "moonlight.configuration.test_category.test_json": "测试 JSON",
    "moonlight.configuration.test_category.test_json.description": "原始 JSON 值，在带语法高亮的文本框中编辑",
    "moonlight.configuration.test_category.test_list": "测试列表",
    "moonlight.configuration.test_category.test_list.description": "自由文本字符串列表，在子页面中编辑",
    "moonlight.configuration.test_category.test_percent": "测试百分比",
    "moonlight.configuration.test_category.test_percent.description": "百分比，以显示 % 的滑块编辑",
    "moonlight.configuration.test_category.test_plain_bool": "测试普通布尔",
    "moonlight.configuration.test_category.test_plain_bool.description": "普通布尔值，绘制为开/关按钮",
    "moonlight.configuration.test_category.test_range": "测试范围",
    "moonlight.configuration.test_category.test_regex": "测试正则",
    "moonlight.configuration.test_category.test_regex.description": "带实时语法高亮的正则表达式",
    "moonlight.configuration.test_category.test_schema": "测试 Schema",
    "moonlight.configuration.test_category.test_schema.description": "带 CodecUI schema 的 codec 对象，通过生成的表单编辑：record 和列表变为可导航的子页面，id 和标签获得注册表下拉框，map 回退到 JSON 编辑器",
    "moonlight.configuration.test_category.test_schema_advanced": "测试 Schema（高级）",
    "moonlight.configuration.test_category.test_schema_advanced.description": "schema 表单：长整型、十六进制颜色、正则、可选值、有界列表、对、分发、either、分发 map、递归、原始值",
    "moonlight.configuration.test_category.test_schema_list": "测试 Schema 列表",
    "moonlight.configuration.test_category.test_schema_list.description": "codec 对象列表：配置自身页面即为列表，可直接增删条目",
    "moonlight.configuration.test_category.test_schema_map": "测试 Schema 映射",
    "moonlight.configuration.test_category.test_schema_map.description": "schema 映射",
    "moonlight.configuration.test_category.test_string": "测试字符串",
    "moonlight.configuration.test_category.test_string.description": "字符串字段",
    "moonlight.configuration.test_category.test_time": "测试时间",
    "moonlight.configuration.test_category.test_vec3": "测试 Vec3",
    "moonlight.configuration.test_category.test_vec3i": "测试 Vec3i",
    "moonlight.configuration.test_category.test_world_reload": "测试（需重载世界）",
    "moonlight.configuration.test_category.test_world_reload.description": "需要重载世界才能生效的值（显示地球图标）",
    "moonlight.configuration.test_date": "测试日期",
    "moonlight.configuration.test_date.day": "日",
    "moonlight.configuration.test_date.month": "月",
    "moonlight.configuration.test_feature": "测试特性",
    "moonlight.configuration.test_feature.feature_speed": "特性速度",
    "moonlight.configuration.test_feature.feature_speed.description": "仅在特性开启时有意义",
    "moonlight.configuration.test_range": "测试范围",
    "moonlight.configuration.test_record_bean": "测试 Record Bean",
    "moonlight.configuration.test_record_bean.amount": "数量",
    "moonlight.configuration.test_record_bean.label": "标签",
    "moonlight.configuration.test_sub_feature": "测试子特性",
    "moonlight.configuration.test_sub_feature.sub_power": "子功率",
    "moonlight.configuration.test_sub_feature.sub_power.description": "父特性关闭时，此特性读取为 false",
    "moonlight.configuration.test_time": "测试时间",
    "moonlight.configuration.test_time.hour": "时",
    "moonlight.configuration.test_time.minute": "分",
    "moonlight.configuration.test_vec3": "测试 Vec3",
    "moonlight.configuration.test_vec3i": "测试 Vec3i",
    "moonlight.nautilus_studio.map_marker": "地图标记",
    "moonlight.nautilus_studio.villager_trade": "村民交易",
    "tooltip.moonlight.block_tags": "方块标签：",
    "tooltip.moonlight.item_tags": "物品标签：",
    "tooltip.moonlight.media.akliz": "需要服务器？用 Akliz 开一个",
    "tooltip.moonlight.media.curseforge": "CurseForge 页面",
    "tooltip.moonlight.media.discord": "模组 Discord",
    "tooltip.moonlight.media.github": "模组 Wiki",
    "tooltip.moonlight.media.ko_fi": "请我喝杯咖啡",
    "tooltip.moonlight.media.link": "模组页面",
    "tooltip.moonlight.media.marketplace": "来 Marketplace 看看我们！",
    "tooltip.moonlight.media.modrinth": "Modrinth 页面",
    "tooltip.moonlight.media.partner_server": "需要服务器？用 %s 开一个",
    "tooltip.moonlight.media.patreon": "在 Patreon 上支持我 :D",
    "tooltip.moonlight.media.twitter": "Twitter 页面",
    "tooltip.moonlight.media.youtube": "YouTube 频道",
}

CREATE = {
    "create.gui.stock_keeper.click_to_cycle": "点击切换",
    "create.gui.stock_keeper.jei_sync.none": "不同步",
    "create.gui.stock_keeper.jei_sync.none.description": "库存管理员与配方查看器的搜索相互独立",
    "create.gui.stock_keeper.jei_sync.sync_both": "与配方查看器双向同步",
    "create.gui.stock_keeper.jei_sync.sync_both.description": "库存管理员与配方查看器的搜索将保持同步",
    "create.gui.stock_keeper.jei_sync.sync_from_jei": "从配方查看器同步",
    "create.gui.stock_keeper.jei_sync.sync_from_jei.description": "在配方查看器中的搜索会镜像到库存管理员",
    "create.gui.stock_keeper.jei_sync.sync_from_stock_keeper": "从库存管理员同步",
    "create.gui.stock_keeper.jei_sync.sync_from_stock_keeper.description": "在库存管理员中的搜索会镜像到配方查看器",
    "create.keyinfo.alt_modifier": "Alt 修饰键",
    "create.keyinfo.ctrl_modifier": "Ctrl 修饰键",
    "create.keyinfo.shift_modifier": "Shift 修饰键",
    "create.schematic.tool.flip.description.2": "",
    "create.schematic.tool.flip.description.3": "",
    "create.schematic.tool.move.description.2": "",
    "create.schematic.tool.move.description.3": "",
    "create.schematic.tool.move_y.description.2": "",
    "create.schematic.tool.move_y.description.3": "",
    "create.schematic.tool.print.description.3": "",
    "create.schematic.tool.rotate.description.2": "",
    "create.schematic.tool.rotate.description.3": "",
    "tag.item.c.foods.dough.wheat": "小麦面团",
}

MODERNFIX = {
    "modernfix.option.mixin.bugfix.buffer_builder_leak": "尝试解决部分模组构造 BufferBuilder 对象导致内存泄漏的问题。在极少数情况下可能导致 JVM 崩溃并生成 hs_err_pid 文件。如果你遇到此类崩溃，可尝试禁用此选项。",
    "modernfix.option.mixin.bugfix.extra_experimental_screen": "修复重新打开以实验性功能创建的世界时，首次仍会显示实验性功能警告的问题。",
    "modernfix.option.mixin.bugfix.forge_at_inject_error": "修复 Forge 早期错误处理代码中的重大疏漏：该问题会导致模组只有部分内容加载，通常会让游戏直接崩溃而不是显示预期的错误界面。此问题已在 NeoForge 中修复，新版 Forge 也已修复。",
    "modernfix.option.mixin.bugfix.missing_block_entities": "Hypixel 发送的区块缺少部分方块实体数据，导致箱子等不可见。此选项通过在客户端创建所需数据来规避该问题。对行为正常的服务器或单人游戏无效。",
    "modernfix.option.mixin.bugfix.restore_old_dragon_movement": "修复 MC-272431：末影龙无法像 1.13 及更早版本那样俯冲至传送门。这会导致末影龙的飞行与现代玩家的习惯大不相同，且会移除一循环击杀，因此默认不启用。感谢 Jukitsu 找出原版代码中的这一退化。",
    "modernfix.option.mixin.bugfix.world_screen_skipped": "修复 MC-251068：删除最后一个世界后会回到空的世界列表。",
    "modernfix.option.mixin.feature.blockentity_incorrect_thread": "**这是调试选项，日常游戏不应启用。** 尝试检测在错误线程上与方块实体交互的模组，并携带更多信息使游戏崩溃，而不是抛出难以理解的 ConcurrentModificationException",
    "modernfix.option.mixin.feature.cause_lag_by_disabling_threads": "禁用服务端和区块渲染对工作线程的使用。**这在几乎所有硬件上都会降低性能**，仅当你明确知道自己在做什么时才应在客户端启用，且可能仅适用于物理核心极少（2 核或更少）的硬件。在这类罕见情况下，它可以减少因核心争用导致的卡顿尖峰。",
    "modernfix.option.mixin.feature.registry_event_progress": "在加载过程的部分阶段将 Forge 加载界面放到后台线程运行，以便在注册内容时显示进度。可能与某些 GPU 驱动（如 macOS）存在兼容性问题，整合包中请勿默认启用。",
    "modernfix.option.mixin.feature.remove_chat_signing": "阻止 Minecraft 客户端获取聊天签名的密钥对。这会禁用客户端签名聊天消息的能力（类似 No Chat Reports，但方式更简单，尽管对用户不太友好）。",
    "modernfix.option.mixin.feature.remove_telemetry": "阻止 Minecraft 客户端向 Mojang 发送遥测数据。对模组客户端而言这些遥测数据通常无关紧要。",
    "modernfix.option.mixin.feature.suppress_narrator_stacktrace": "防止 Linux 上讲述人加载失败时记录超长堆栈跟踪（通常因未安装 libflite）。",
    "modernfix.option.mixin.perf.chunk_meshing": "对原版区块网格构建逻辑做一些小优化（若区块渲染已被其他模组整体替换，则无效果）。",
    "modernfix.option.mixin.perf.compress_unihex_font": "更高效地存储 Unicode 字体的字形。感谢 @AnAwesomGuy 提供的技巧。",
    "modernfix.option.mixin.perf.dynamic_resources.ldlib": "LDLib 的动态资源兼容性补丁",
    "modernfix.option.mixin.perf.faster_structure_location": "提高埋藏宝藏等结构的定位速度。",
    "modernfix.option.mixin.perf.forge_registry_alloc": "修复 Forge 中更多导致热点注册表方法过度分配内存的疏漏。",
    "modernfix.option.mixin.perf.memoize_creative_tab_build": "以兼容 JEI/EMI 等模组时序要求的方式改进原版对创造模式物品栏内容的缓存。可减少整合包中首次打开创造物品栏时的卡顿尖峰。",
    "modernfix.option.mixin.perf.potential_spawns_alloc": "优化 Forge 查找潜在生成生物的事件。在无模组修改潜在生成物时减少内存分配和重建权重列表的开销。",
    "modernfix.option.mixin.perf.ticking_chunk_alloc": "优化原版区块 tick 以减少内存分配。",
    "modernfix.option.mixin.perf.worldgen_allocation": "优化原版的部分世界生成逻辑以减少对象分配。",
    "modernfix.redirector_installed": "ModernFix 检测到已安装 Redirector。Redirector 已知会引发许多奇怪且难以调试的问题，强烈建议移除。",
}

MISC = {
    "tag.block.farmersdelight.cabinets.wooden": "木质橱柜",
    "tag.block.farmersdelight.mineable.knife": "可用刀挖掘",
    "supplementaries.configuration.globe.sepia_globe.description": "若禁用 antique_ink（古董墨水）特性，深褐色地球仪将自动停用",
    "supplementaries.configuration.plunderer.galleon.description": "若禁用 rope（绳索）特性，海盗船将自动停用",
}
